apiVersion: apps/v1
kind: Deployment
metadata:
    name: order-deployment
    labels:
        app: order-app
spec:
    replicas: 3
    selector:
        matchLabels:
            app: order-app
    template:
        metadata:
            labels:
                app: order-app
        spec:         
          containers:
          - name: order-container
            image: kiranbirkaur/ordersservice
            ports: 
            - containerPort: 8020