apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-deployment
    labels:
        app: user-app
spec:
    replicas: 3
    selector:
        matchLabels:
            app: user-app
    template:
        metadata:
            labels:
                app: user-app
        spec:         
          containers:
          - name: user-container
            image: kiranbirkaur/userservice
            ports: 
            - containerPort: 8010